#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width	0
bspc config borderless_monocle	true

bspc config window_gap		5
bspc config split_ratio         0.50
bspc config gapless_monocle     true

# Autostart Apps
sxhkd &
~/.config/polybar/launch.sh & disown
